# Generated by Django 4.1.6 on 2023-02-11 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('C', 'completed'), ('P', 'Pending')], max_length=2)),
                ('priority', models.CharField(choices=[('6', '6'), ('5', '5'), ('4', '4'), ('2', '2'), ('1', '1'), ('3', '3'), ('9', '9'), ('7', '7'), ('10', '🔟'), ('8', '8')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userinfo')),
            ],
        ),
    ]
